### ISSUE TITLE
Config Wizard

### ISSUE THREAD

**Issue by TimPasquini** [rishikanthc/Scriberr#33]
I'm not sure how or why, but it appears I was never presented with the Configuration Wizard on first run. 

Is there a way to trigger it manually?

**Comment by rishikanthc** [comment]
Are you upgrading from a previous version ? If so it needs to be redeployed from scratch. Unfortunately this version is a breaking change. 
The wizard runs if it can't find the database tables. If they are already created then it will not run. You can manually trigger it by navigating to /wizard

**Comment by TimPasquini** [comment]
No, this was a totally fresh and first time install through unraid. Navigating to /wizard gives a 400 error. I've tried nuking the containers and their volumes to give it a fresh start and now it wont render anything beyond the Name and the Dark/Light theme button.

Looks like some sort of permissions error in the logs.

```
API records | Error fetching records ClientResponseError 403: Only admins can perform this action.
    at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async GET (file:///app/build/server/chunks/_server.ts-Yae5p7L2.js:10:21)
    at async render_endpoint (file:///app/build/server/index.js:1528:20)
    at async resolve2 (file:///app/build/server/index.js:4015:22)
    at async Object.authentication [as handle] (file:///app/build/server/chunks/hooks.server-BmiKiuxm.js:51:20)
    at async respond (file:///app/build/server/index.js:3910:22)
    at async fetch (file:///app/build/server/index.js:3660:26) {
  url: 'http://localhost:8080/api/collections/templates/records?page=1&perPage=500&skipTotal=1',
  status: 403,
  response: {
    code: 403,
    message: 'Only admins can perform this action.',
    data: {}
  },
  isAbort: false,
  originalError: {
    url: 'http://localhost:8080/api/collections/templates/records?page=1&perPage=500&skipTotal=1',
    status: 403,
    data: {
      code: 403,
      message: 'Only admins can perform this action.',
      data: {}
    }
  }
}
templates =====  {
  url: 'http://localhost:8080/api/collections/templates/records?page=1&perPage=500&skipTotal=1',
  status: 403,
  response: {
    code: 403,
    message: 'Only admins can perform this action.',
    data: {}
  },
  isAbort: false,
  originalError: {
    url: 'http://localhost:8080/api/collections/templates/records?page=1&perPage=500&skipTotal=1',
    status: 403,
    data: {
      code: 403,
      message: 'Only admins can perform this action.',
      data: {}
    }
  },
  name: 'ClientResponseError 403'
}'```

**Comment by TimPasquini** [comment]
Just brainstorming, but I'm wondering if it's a pocketbase issue? I'm realizing now that there is no environmental variable for the pocketbase port, just the URL. I can't put pocketbase on 8080 as it's already in use by something else so I'm using it at port 8086 but don't appear to have a way to point at that port.

**Comment by rishikanthc** [comment]
This is because of the auth token. Open your browser navigate to scriberr. Right click inspect and go to the storage tab and check for cookies. You will find an auth cookie stored by the app. Delete it. Then try again. 
Each time you do a fresh install the auth token changes. Right now the app doesn't auto refresh and fetch a new one. So the old one stays in the browser and because of that it throws a permission error. 
Just delete that cookie and everything should work again. 
Let me know if you still face issues

**Comment by rishikanthc** [comment]
Also just wanted to confirm. You're running 0.3.0 right ?

**Comment by TimPasquini** [comment]
Ok, clearing the cookie got me back to the interface. Navigating to /wizard still did not work so I took a look at the docker image tag I was pulling and it looks like the tag for "latest" was last updated 23 days ago while "0.3.0" was updated 18 days ago so I switched the tag I was using to that one and I've got it up and running now. You might want to update the "latest" tag since that is what most people will likely default to using.

Ultimately, I did need to disable my service running on 8080 so I could give that port to pocketbase. I run my docker stuff through unRaid so I don't think I'm using compose (or at least not directly), is there a way to set this port by setting an environmental variable, similar to REDIS_PORT?

**Comment by rishikanthc** [comment]
Ahh gotcha. Thanks for pointing out. Yes I'll update the tag. 
Regarding the port for pocketbase right now there's no way to change it. But you shouldn't have to disable your service because scriberr uses port 8080 on the localhost which puts it internal to the container. So there's no need to expose 8080 publicly.
Anyways no worries. The next release should solve all this. The next release will be a svelte 5 rewrite and I'll be moving away from pocketbase and put the db on a separate container. So things should be a lot more better and smoother to setup.

**Comment by TimPasquini** [comment]
Ok, I will try that out. Either way I appear to have it working. I'll look out for the new update as well!
