### ISSUE TITLE
Docker Compose error: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by ericsharma** [rishikanthc/Scriberr#5]
Using the docker compose in the Readme I get the following error on M1 macs: 

no matching manifest for linux/arm64/v8 in the manifest list entries

It works on my linux machine but in the Readme you mention running it on your M2 mac which is arm64 same as my M1s. Any ideas what my issue is?

**Comment by rishikanthc** [comment]
The arm docker image isn't available yet. I didn't push the docker image. Will do so today.

**Comment by rishikanthc** [comment]
Arm image is available now. Try again now and it should work

**Comment by unfixa1** [comment]
The error message encountered when using Docker Compose on an M1 Mac is "no matching manifest for linux/arm64/v8 in the manifest list entries". This error is usually because the Docker image used does not support the ARM64 architecture. It is recommended that you use [Servbay](servbay.com) to replace docker to deploy the development environment. Servbay supports the arm architecture.
